name: naruto_the_ninja_way
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_spinkit: "^4.1.2"
  animated_text_kit: ^4.2.1
  ionicons: ^0.1.2
  flutter_staggered_animations: ^1.0.0
  url_launcher: ^6.0.7
  flutter_slidable: ^0.6.0
  carousel_slider: ^4.0.0
  pie_chart: ^5.0.0


  
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - images/general/
    - images/characters/Shino/
    - images/characters/Shibi/
    - images/characters/Torune/
    - images/villages/
    

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For

  fonts:
    - family: Pacifico
      fonts:
        - asset: fonts/Pacifico-Regular.ttf
    
    - family: PatuaOne
      fonts:
        - asset: fonts/PatuaOne-Regular.ttf    
    
    - family: Quattrocento
      fonts:
        - asset: fonts/Quattrocento-Regular.ttf
    - family: Signika
      fonts:
        - asset: fonts/Signika-Regular.ttf
    - family: Goldman
      fonts:
        - asset: fonts/Goldman-Bold.ttf
       
    
    - family: ZillaSlab
      fonts:
        - asset: fonts/ZillaSlab-BoldItalic.ttf
    
    - family: Goldman
      fonts:
        - asset: fonts/Goldman-Bold.ttf


    - family: HammersmithOne
      fonts:
        - asset: fonts/HammersmithOne-Regular.ttf

    - family: AlfaSlabOne
      fonts:
        - asset: fonts/AlfaSlabOne-Regular.ttf

    - family: BreeSerif
      fonts:
        - asset: fonts/BreeSerif-Regular.ttf

    - family: CreteRound
      fonts:
        - asset: fonts/CreteRound-Regular.ttf

    - family: ConcertOne
      fonts:
        - asset: fonts/ConcertOne-Regular.ttf  

    - family: Grandstander
      fonts:
        - asset: fonts/Grandstander-VariableFont_wght.ttf
    - family: DancingScript
      fonts:
        - asset: fonts/DancingScript-VariableFont_wght.ttf


    - family: Fredoka One
      fonts:
        - asset: fonts/FredokaOne-Regular.ttf

    - family: Acme
      fonts:
        - asset: fonts/Acme-Regular.ttf
  
    - family: Ranchers
      fonts:
        - asset: fonts/Ranchers-Regular.ttf

    - family: Monoton
      fonts:
        - asset: fonts/Monoton-Regular.ttf

    - family: Lobster
      fonts:
        - asset: fonts/Lobster-Regular.ttf

    - family: Naruto
      fonts:
        - asset: fonts/naruto.ttf