import 'package:naruto_the_ninja_way/Models/character.dart';
import 'package:flutter/material.dart';

class listOfCharacters {
  final List<character> characters = [
    character(
        name: "Aburame Shino",
        id: 0,
        height: "175.1 cm",
        weight: "56.6 kg",
        dob: "January 23",
        coverImage: 'images/characters/Shino/cover.jpg',
        clan: "Aburame",
        age: "16",
        rank: "Chunin",
        village: "Leaf",
        villageSymbol: "images/villages/leaf_headband.gif",
        firstAppearance: "Episode 1",
        sex: "Male",
        centerVillageSymbol: 'images/villages/leafCenter.png',
        signatureMove: "Kikaichuu no Jutsu",
        quote:
            "Even if our enemy is a small bug, we will not underestimate it.",
        images: [
          'images/characters/Shino/1.png',
          'images/characters/Shino/2.png',
          'images/characters/Shino/3.png',
          'images/characters/Shino/4.png',
          'images/characters/Shino/5.png',
          'images/characters/Shino/6.png',
        ],
        drank: 17,
        arank: 1,
        brank: 9,
        crank: 17,
        srank: 0,
        caseStudy:
            "Shino's appearances in the series are few and far between. Shino has yet to take the forefront in any series arc, instead acting as a minor support player. His strong, unshakable confidence, mysterious look and cool aura make him popular among fans despite his ultimately creepy habits. His analytical skill and cautious nature often annoy Kiba, who thinks Shino is trying to become the de facto leader of the team.Shino was assigned along with Hyuuga Hinata and Inuzaka Kiba to the tutelage of Yuuhi Kurenai. Even to his own team, he remained much of an enigma. His true abilities were first seen in the Chuunin Exam when he faced Zaku. A hole opened up in Shino�s face and to the disgust of most watching, hordes of bugs began to crawl all over his skin. Shino revealed to his opponent that the bugs would eat his chakra, rendering him too weak to move. Trapping Zaku between himself and his army, Shino demanded surrender. When Zaku threatened to attack both of them simultaneously, Shino revealed that he had a hidden surprise, sending his bugs inside Zaku's weapon to jam it. Because Zaku's weapons were integrated into his physical arms, they were damaged beyond repair. Shino explains that having a trump card or ace in the hole is vital in battle.Because of his victory, Shino advanced to the finals of the exam, slated to face Kankurou. However, when their match was to take place, Kankurou instantly gave in. The reason, it was later revealed, was to prevent anyone seeing his hidden techniques with his puppet, Karasu. Gaara�s instability then caused the premature plan of the combined Sand and Sound invasion. Shino watched as Kankurou and his siblings retreated to help Gaara, following them in secret. As Kankurou prepared to take on Sasuke to slow him down, Shino stepped in and demanded the match he had been deprived of.Demonstrating some of the Destruction Bugs� more unusual abilities, Shino used them to make a decoy of himself, while moving close to Kankurou to strike at him. While Shino�s hand-to-hand skills were none too impressive, he had deliberately made a feint to plant a female bug on Kankurou, giving the rest of his bugs a permanent target to chase after. Despite Kankurou managing to catch Shino with a poison gas bomb, Shino forced the stalemate as his bugs tracked Kankurou down and left him paralyzed after eating all his chakra. Shino�s father later appeared and saved his life, injecting him with his own bugs that ate away the poison. Later, Shino would be absent from the mission to rescue Sasuke, on a mission with his father. Over the next few years Shino would again take the Chuunin Exam and finally be promoted to Chuunin.Upon Naruto's return to the village, Shino was hurt that he was not quickly recognized. Some weeks later, Team 8 under the leadership of Kakashi joined with Team 7 to hunt down Uchiha Itachi in the hopes of finding Sasuke. The team set out and managed to locate Akatsuki member Tobi. Shino tried to use his bugs, but Tobi's ability to phase through matter and transport himself allowed him to avoid harm. When the team eventually tracked down Sasuke's location, they came upon the ruins of Sasuke and Itachi's fight. Both brothers were gone, leaving the teams empty handed, so they returned to Konoha."),
    character(
      id: 1,
      centerVillageSymbol: 'images/villages/leafCenter.png',
      name: "Aburame Shibi",
      age: "39",
      caseStudy:
          "Aburame Shibi is the father of Aburame Shino. Like his son, his body is also inhabited by the destruction bugs.",
      clan: "Aburame",
      firstAppearance: "Episode 79",
      images: [
        'images/characters/Shibi/3.png',
        'images/characters/Shibi/2.png',
        'images/characters/Shibi/1.png',
        'images/characters/Shibi/4.png',
        'images/characters/Shibi/5.png',
      ],
      coverImage: 'images/characters/Shibi/covereImage.jpg',
      quote: "NA",
      rank: "Jounin",
      sex: "Male",
      signatureMove: "NA",
      village: "Leaf",
      villageSymbol: "images/villages/leaf_headband.gif",
      height: "181.3 cm",
      arank: -1,
      brank: -1,
      crank: -1,
      dob: "September 7",
      drank: -1,
      srank: -1,
      weight: "68.9 kg",
    ),
    character(
      age: "NA",
      id: 2,
      coverImage: 'images/characters/Torune/cover.jpg',
      srank: -1,
      crank: -1,
      brank:-1 ,
      arank: -1,
      drank:-1 ,
      height: "NA",
      dob: "NA",
      weight: "NA",
      caseStudy:
          "Aburame Torune is an ANBU Root member in Hidden Leaf Village. He attended the five Kage summit with Danzou. Because masks were not allowed at the summit, Torune had to go in his normal clothing. He and Fuu are regarded as the most skilled Root members.",
      clan: "Aburame",
      firstAppearance: "Shippuuden Episode 198",
      images: [
        'images/characters/Torune/1.png',
        'images/characters/Torune/2.png',
        'images/characters/Torune/3.png',
        'images/characters/Torune/4.png',
      ],
      name: "Aburame Torune",
      quote: "NA",
      rank: "Anbu",
      sex: "Male",
      signatureMove: "NA",
      village: "Leaf",
      villageSymbol: 'images/villages/leaf_headband.gif',
      centerVillageSymbol: 'images/villages/leafCenter.png',
    ),
    character(
      weight: "137 kg",
      srank: -1,
      drank: -1,
      dob: "January 11",
      crank: -1,
      centerVillageSymbol: 'images/villages/rockCenter.png',
      brank: -1,
      arank: -1,
      height: "200 cm",
      villageSymbol: "images/villages/rock_headband.gif",
      village: "Rock",
      signatureMove: "NA",
      sex: "Male",
      rank: "Jounin",
      quote: "NA",
      name: "Akatsuchi",
      images: [
        'images/characters/Akatsuchi/1.png',
        'images/characters/Akatsuchi/2.png',
        'images/characters/Akatsuchi/3.png',
      ],
      firstAppearance: "Shippuuden Episode 199",
      clan: "Unknown",
      caseStudy: "Akatsuchi is a ninja in Hidden Rock village. He attended the five Kage summit with the Tsuchikage.",
      age: "20",
      coverImage: 'images/characters/Akatsuchi/coverImage.jpg',
      id: 3,

    ),
  ];

  List<character> get allCharacters {
    return [...characters];
  }
}
